_target_: proteinworkshop.models.graph_encoders.gear_net.GearNet
input_dim: ${resolve_feature_config_dim:${features},scalar_node_features,${task},true}
num_relation: ${resolve_num_edge_types:${features}}
num_layers: 6
emb_dim: 512
short_cut: True
concat_hidden: True
batch_norm: True
num_angle_bin: null
activation: "relu"
pool: sum
